### ISSUE TITLE
Login page flashes then disappears - isConfigured endpoint returning wrong data

### ISSUE THREAD

**Issue by tluj** [CyferShepard/Jellystat#489]
Been trying to figure this out for a few days. Login/setup page briefly appears then vanishes, leaving just a black background. Happens in Firefox, LibreWolf, Chrome - tried incognito, cleared cache, no ad blockers. Same behavior on fresh install.

Dug into it and found the issue:
​```
$ curl -s http://localhost:3000/auth/isConfigured
{"version":"1.1.7"}
​```

That endpoint is returning the version string instead of the expected `{"isConfigured": true/false}`. The frontend doesn't know how to handle that response so it crashes.

Tested on:
- 1.1.6, 1.1.7, and unstable branch - all same problem
- Fresh database wipe didn't help
- Podman rootless on Fedora
- Postgres 15-alpine

The app_config table exists and has a row, but the endpoint just ignores it and returns version info regardless.

Container logs show it starting fine:
​```
[JELLYSTAT] Database exists. Skipping creation
[JELLYSTAT] Server listening on http://0.0.0.0:3000/
​```
No errors, it just serves the wrong response.

**Comment by CyferShepard** [comment]
Hey @tluj , this is an example of the expected response from this endpoint. `{"state":2,"version":"1.1.8"}` do you see the `state` property anywhere in your response?

**Comment by CyferShepard** [comment]
Can you try pulling latest `unstable`, i think i see where the issue could be occurring, and i added logging to that point. Check again and please provide the logs from docker. Your looking for `Error fetching config:`

**Comment by tluj** [comment]
No, there's no `state` property in my response. I only see `{"version":"1.1.7"}` and `{"version":"1.1.8"}`

Tested both:

**unstable:**
```
Error fetching config: TypeError: db.query is not a function
Error fetching config: TypeError: db.query is not a function
Error fetching config: TypeError: db.query is not a function
Error fetching config: TypeError: db.query is not a function
```

**stable (1.1.7):**
No "Error fetching config" in logs (logging not present), but shows:
```
[ActivityMonitor] Config not ready, starting with default interval: 1000ms
```

Both are returning `{"version":"..."}` from `/auth/isConfigured` - no `state` property.

**Comment by CyferShepard** [comment]
Can you provide your hardware information as well? Il look into this tomorrow. For some reason is not loading the database class on your system. But thats weird because if it was a db issue it would not be able to load at all

**Comment by tluj** [comment]
Fedora 42
Podman 5.7.1 (rootless)
amd64/x86_64

**Comment by martijndhondt** [comment]
I had the same issue, the docker-compose needs all the values for postgres:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jellystatpass
      POSTGRES_IP: jellystat-db
      POSTGRES_DB: jellystat
      POSTGRES_PORT: 5432
The error wen't away after that

**Comment by tluj** [comment]
Resolved. The issue was caused by my configuration diverging from the official docker-compose. I was using a custom database name and user (POSTGRES_DB=jellystat, POSTGRES_USER=jellystat) instead of the defaults. I cleared the postgres data directory and aligned with the upstream setup (connecting as postgres, using POSTGRES_IP, letting the app create its own default database), the db.query is not a functoin error is now gone and everything works on 1.1.8.
